### PR TITLE
Re-implemented tfidf scorer.

### PR DESCRIPTION
**Pull request by krisrogers**
Signficant improvements on memory and cpu overhead.
Removed cosine similarity, scoring is now done by accumulating tf-idf values for each query term present in the frame.

### CODE REVIEW

**Comment by krisrogers** [comment]
Can compare performance with master branch via:
[profile_scoring.txt](https://github.com/Kapiche/caterpillar/files/387717/profile_scoring.txt)

**Comment by rstuart85** [comment]
Here are two profile dumps from master and this branch. If you `pip install snakeviz` then run `snakeviz <profile_file>` you get a great output of the time being used.

There has been a significant reduction in the time taken to do the search and scoring which is fantastic. What really sticks out now is that parsing the query, even for a simple query, takes almost half the time. Worryingly, it take more time than the disk IO!! 

I think this is the next place we need to take a look at in the future. I'll create an issue.

[searching_benchmark_new.profile.txt](https://github.com/Kapiche/caterpillar/files/389619/searching_benchmark_new.profile.txt)
[searching_benchmark_old.profile.txt](https://github.com/Kapiche/caterpillar/files/389620/searching_benchmark_old.profile.txt)

**Comment by rstuart85** [comment]
Also, FYI, this is the profile code I am using. If you put it in the caterpillar directory, it should work with no modifications.

[profile_scoring.txt](https://github.com/Kapiche/caterpillar/files/389623/profile_scoring.txt)

**Comment by rstuart85** [comment]
@krisrogers: We can make searching 30% faster by using pre-compiled grammars from lrparsing. See [here](http://lrparsing.sourceforge.net/doc/html/#lrparsing.pre_compile_grammar). It appears to be a trivial change. Should we just do it in this pull request?

**Comment by rstuart85** [comment]
With the pre-compile of the grammar, IO now accounts for 75% of the search time.

**Pull request merged**
